#ifndef GAMUTPLOTTER_CONFIG
#define GAMUTPLOTTER_CONFIG

/* JPEG XL capability checker */
#cmakedefine HAVE_JPEGXL 1

#define PROJECT_VERSION "@PROJECT_VERSION@"
#define PROJECT_VERSION_MAJOR "@PROJECT_VERSION_MJAOR@"
#define PROJECT_VERSION_MINOR "@PROJECT_VERSION_MINOR@"
#define PROJECT_VERSION_PATCH "@PROJECT_VERSION_PATCH@"

#endif
